version: 2
updates:
  - package-ecosystem: "nuget"            # las dependencias del backend
    directory: "/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"              # las del frontend
    directory: "/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"   # ¡tus actions también son dependencias!
    directory: "/"
    schedule:
      interval: "weekly"
